include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    omit_local_variable_types: false

dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/all.yaml
  rules:
    # Style
    - format-comment: false
    - prefer-match-file-name: false
    - newline-before-return: false
    - arguments-ordering: false
    - prefer-single-widget-per-file: false
    # Code
    - avoid-dynamic: true
    - avoid-ignoring-return-values: false
    - prefer-static-class: false
    - no-equal-arguments: false
    - no-magic-number: false
    # - prefer-extracting-callbacks:
    #     allowed-line-count: 10
